---
name: Deploy Governance Tags

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - none
  # schedule:
  #  - cron: 0 0 * * sun #every sunday at 00.00
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  MODULE_NAME: governance-tags

jobs:
  deploy_canary:
    name: Deploy Governance Tags Canary
    environment:
      name: Canary
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_SHORT_NAME: canary
      PREFIX: lz-canary
      TAGOWNER: maras@netdesign.dk
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Install dependencies from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Resources,Az.ResourceGraph
          Import-Module Az.Resources,Az.ResourceGraph

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: deploy governance tags
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/misc/powershell/Assign-Tags.ps1 -Prefix ${{ env.PREFIX }} -TagOwner ${{ env.TAGOWNER }}
          azPSVersion: latest

  deploy_prod:
    name: Deploy Governance Tags Production
    environment:
      name: Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      ENVIRONMENT_SHORT_NAME: prod
      PREFIX: lz
      TAGOWNER: maras@netdesign.dk
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v3
      - name: Install dependencies from PSGallery
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Resources,Az.ResourceGraph
          Import-Module Az.Resources,Az.ResourceGraph

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_MANAGEMENT_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: deploy governance tags
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ${{ github.workspace }}/misc/powershell/Assign-Tags.ps1 -Prefix ${{ env.PREFIX }} -TagOwner ${{ env.TAGOWNER }}
          azPSVersion: latest
